controller_manager:
  ros__parameters:
    update_rate: 200

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    diff_drive_controller:
      type: diff_drive_controller/DiffDriveController

    servo_controller:
      type: forward_command_controller/ForwardCommandController

diff_drive_controller:
  ros__parameters:
    left_wheel_names: ["Revolucion_1", "Revolucion_3"]
    right_wheel_names: ["Revolucion_2", "Revolucion_4"]
    wheel_separation: 0.121
    wheel_radius: 0.05
    use_stamped_vel: false
    open_loop: false

servo_controller:
  ros__parameters:

    joints:
      - Revolucion_5
      - Revolucion_6
      - Revolucion_7
      - Revolucion_8
      - Revolucion_9
      - Revolucion_10
      - Revolucion_11
      - Revolucion_12
      - Revolucion_13
      - Revolucion_14
      - Revolucion_15
    interface_name: position
    
joint_state_broadcaster:
  ros__parameters: {}
